name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: yarn
    - name: Prepack from TypeScript/ES6 source
      run: yarn prepack
    - name: Launch tests
      run: yarn test

  alpine-docker:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Try to build dummy Alpine Docker image
      run: docker build -t excalidraw-cli:latest .
